CREATE DATABASE FACEBOT
USE FACEBOT

CREATE TABLE COMMENTS_MADE(
Id int IDENTITY(1,1) PRIMARY KEY,
Friend varchar(100) NULL,
Created_At Datetime NULL
)

SELECT * FROM COMMENTS_MADE

CREATE TABLE COMMENTS_LOG(
Id int IDENTITY(1,1) PRIMARY KEY,
Log varchar(500) NULL,
Friend varchar(100) NULL,
Created_At Datetime NULL
)

SELECT * FROM COMMENTS_LOG


